CREATE DATABASE CERTIFICADOS;

USE CERTIFICADOS;

CREATE TABLE CERTIFICADO (
	ID_CERTIFICADO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    CPF VARCHAR(20),
    RG VARCHAR(20),
    CIDADE VARCHAR(20) NOT NULL,
    CONCLUSAO DATE NOT NULL,
    VALIDACAO VARCHAR(100) NOT NULL
);